package com.amigoscode.customer;

/*
    ref: https://www.baeldung.com/java-record-keyword
    Use record instead of class due to its ability in JDK14.

    We can replace our repetitious data classes with records.

    Records are immutable data classes that require only the type
    and name of fields.

    The equals, hashCode, and toString methods,
    as well as the private, final fields and
    public constructor, are generated by the Java compiler.

    Can be used with JPA.
*/
public record CustomerRegistrationRequest(
        String firstName,
        String lastName,
        String email
) {

}